### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.

server:
  port: 8000

spring:
  thymeleaf:
    cache: false

### isnt working in application.yml (works in application.properties)
#spring:
#  main:
#    banner-mode: off
