### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.

#server:
#  port: 8000

spring:
  thymeleaf:
    cache: false
#  datasource:
#    url: jdbc:mysql://localhost:3306/readinglist
#    username: root
#    password: jovica12
#    driver-class-name: com.mysql.jdbc.Driver

### isnt working in application.yml (works in application.properties)
#spring:
#  main:
#    banner-mode: off

server:
  port: 8000
#  ssl:
#    key-store: file://mykeys.jks
#    key-store-password: jovica12
#    key-password: jovica12

#logging:
#  path: /var/logs/
#  file: BookWorm.log
#  level:
#    root: WARN
#    org.springframework.security: DEBUG
